apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    name: springboot-server
    targetPort: {{ .Values.targetPort }}
  selector:
    app: {{ .Values.appName }}
    tier: backend
  type: ClusterIP