server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://fitness-eureka-service:8761/eureka
spring:
  main:
    web-application-type: reactive
  application:
    name: apiGateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: '*'
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: selfCoach
          #          uri: http://fitness-self-coach-service:8081
          uri: http://localhost:8081
          predicates:
            - Path=/api/selfCoach/**
          filters:
            - JwtAuthenticationFilter


        - id: adminCoachService
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/adminCoachService/**
          filters:
            - JwtAuthenticationFilter


        - id: authorization
          uri: http://localhost:8082
          #          uri: http://fitness-auth-service:8082
          predicates:
            - Path=/api/v1/auth/**