server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:

        - id: selfCoach
          uri: http://localhost:8081
          predicates:
            - Path=/api/selfCoach/**
          filters:
            - JwtAuthenticationFilter

        - id: authorization
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**