server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: authorization
  mail:
    host: smtp.gmail.com
    port: 587
    username: tudormiron19@gmail.com
    password: megedyhsvvtanyfa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 414630485898-1tav66nkrrq0f2jqfnep4i6fi6cakkns.apps.googleusercontent.com
            client-secret: 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

            redirect-uri: http://localhost:8080

  thymeleaf:
    cache: false # true for production
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org.springframework.security: DEBUG