apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-admin-coach-frontend-deployment
  namespace: default
  labels:
    app: fitness-admin-coach-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-admin-coach-frontend-app
      tier: backend
  template:
    metadata:
      labels:
        app: fitness-admin-coach-frontend-app
        tier: backend
    spec:
      tolerations:
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 600 # Increase the toleration period to 600 seconds (10 minutes)
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 600 # Increase the toleration period to 600 seconds (10 minutes)
      containers:
        - name: fitness-app-admin-coach-frontend-container
          image: docker.io/tudormiron/fitness-app-admin-coach-frontend:1.0.7 #{"$imagepolicy": "flux-system:admin-coach-frontend-service-app-img-conf"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "3072Mi"
              cpu: "100m"
            limits:
              memory: "5120Mi"
              cpu: "200m"
      restartPolicy: Always
