apiVersion: v1
kind: Service
metadata:
  # name: {{ .Values.serviceName }}
  name: fitness-admin-coach-frontend-service
  # namespace: {{ .Values.namespace }}
  namespace: default
  labels:
    # app: {{ .Values.appName }}
    app: fitness-admin-coach-frontend-app

spec:
  ports:
  # - port: {{ .Values.port }}
    - port: 3000
      protocol: TCP
      name: springboot-server
      # targetPort: {{ .Values.targetPort }}
      targetPort: 3000
  selector:
    # app: {{ .Values.appName }}
    app: fitness-admin-coach-frontend-app
    tier: frontend
  type: ClusterIP