server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: selfCoach

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  thymeleaf:
    cache: false # true for production
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html

minio:
  accessKey: dAh2wTxgKQK3B6TPi20p
  secretKey: yj7gNRgHJGZlCZUJQYmTmxgnPc4XNW8UEIS6dc5o
#  endpoint: http://192.168.147.140:9000
  endpoint: https://1f7f-109-166-130-164.ngrok-free.app
  put-object-part-size: 5242880


#minio:
#  accessKey: qhxiwuBBB2D3LeJhIr8I
#  secretKey: iSgJZkaZZaV4zYVaPPVlmqjJmXdAwRCr1K64kCnF
#  endpoint: https://172.205.120.186:443
#  put-object-part-size: 5242880

app:
  streaming:
    default-chunk-size: 3145728

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
security:
  basic:
    enabled: false


paypal:
  mode: sandbox
  client:
    id: Ach-mwpZQauApIvPKUPDPV_fls6TuT5emEmkB3fDtKu62CHZ1etTaEXOcuwuZ93YrFFZyER6YsWvd_8G
    secret: EDzjRV8hAl9dO-hrEFEOGyyHPK7pQfi-A9IwqKMEiMC3atxIBtDZdvJj6w_yUU_yZoYE9IEZ_NzMfhX7
    baseUrl: https://api-m.sandbox.paypal.com

