server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: selfCoach

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  basic:
    enabled: false