apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitness-api-gateway-ingress
  namespace: default
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fitness-api-gateway-service
            port:
              number: 8080