apiVersion: apps/v1
kind: Deployment
metadata:
  # name: {{ .Values.deploymentName }}
  name: fitness-admin-coach-backend-deployment
  # namespace: {{ .Values.namespace }}
  namespace: default
  labels:
    # app: {{ .Values.appName }}
    app: fitness-admin-coach-backend-app
spec:
  # replicas: {{ .Values.replicas }}
  replicas: 1
  selector:
    matchLabels:
      # app: {{ .Values.appName }}
      app: fitness-admin-coach-backend-app
      tier: backend
  template:
    metadata:
      labels:
        # app: {{ .Values.appName }}
        app: fitness-admin-coach-backend-app
        tier: backend
    spec: # Pod spec
      containers:
      # - name: fitness-app-auth-container
      - name: fitness-app-admin-coach-backend-container
        # image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        image: docker.io/tudormiron/fitness-app-admin-coach-backend:1.0.10 #{"$imagepolicy": "flux-system:admin-coach-backend-service-app-img-conf"}
        imagePullPolicy: Always
        ports:
        # - containerPort: {{ .Values.port }}
        - containerPort: 8083
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      restartPolicy: Always
