apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: 
  name: api-gateway-app
  namespace: flux-system

spec:
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/apps/api-gateway-app
  prune: true
  wait: true