apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: 
  name: admin-coach-frontend-app
  namespace: flux-system

spec:
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/apps/chat-service-app
  prune: true
  wait: true