apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: 
  name: infrastructure-cluster-manager
  namespace: flux-system

spec:
  dependsOn:
    - name: infrastructure-cluster-issuer
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/certification
  prune: true
  wait: true