apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: 
  name: infrastructure-admin-coach-frontend
  namespace: flux-system

spec:
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/admin-coach-frontend-service-image-config
  prune: true
  wait: true