apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: 
  name: infrastructure-api-gateway
  namespace: flux-system

spec:
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/api-gateway-image-config
  prune: true
  wait: true