apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: 
  name: infrastructure-cluster-issuer
  namespace: flux-system

spec:
  dependsOn:
    - name: infrastructure-cluster-manager
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/config
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/acme/server
          value: https://acme-v02.api.letsencrypt.org/directory
      target:
        kind: ClusterIssuer
        name: letsencrypt