apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: chat-service-app-img-conf
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: chat-service-app-img-conf
  policy:
    semver:
      range: ">=1.0.0"