server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://my-postgres-postgresql.default.svc.cluster.local:5432/authorization

    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: adminCoachService


security:
  basic:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://fitness-eureka-service:8761/eureka

minio:
  accessKey: sX992YF0FHu6v60w7kRy
  secretKey: kekpfoyUyq59u8dv9qtdS2pZJ5TIbmCvudsBw3iQ
  endpoint: https://20.223.251.131:443

app:
  firebase-configuration-file: fitness-app-firebase-adminsdk.json
  firebase-app-name: fitness-app

