server:
  port: 8083

spring:
  boot:
    run:
      jvmArguments: --add-exports java.base/sun.security.provider.certpath=ALL-UNNAMED
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization

    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: adminCoachService


security:
  basic:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

minio:
  accessKey: dAh2wTxgKQK3B6TPi20p
  secretKey: yj7gNRgHJGZlCZUJQYmTmxgnPc4XNW8UEIS6dc5o
#  endpoint: http://192.168.147.140:9000
  endpoint: https://b31f-109-166-130-164.ngrok-free.app

#minio:
#  accessKey: qhxiwuBBB2D3LeJhIr8I
#  secretKey: iSgJZkaZZaV4zYVaPPVlmqjJmXdAwRCr1K64kCnF
#  endpoint: https://172.205.120.186:443

app:
  firebase-configuration-file: fitness-app-firebase-adminsdk.json
  firebase-app-name: fitness-app

