// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsPY1tzUC_8xoxasH4x6GpR0P-Z76M2Tk',
    appId: '1:253020332110:android:36dbb70260c7677f0ae31f',
    messagingSenderId: '253020332110',
    projectId: 'fitness-app-89b40',
    storageBucket: 'fitness-app-89b40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMg7jZofYYVQqrvD8cj_23_JdADgWZk_k',
    appId: '1:253020332110:ios:2b3a83a602dcf0740ae31f',
    messagingSenderId: '253020332110',
    projectId: 'fitness-app-89b40',
    storageBucket: 'fitness-app-89b40.appspot.com',
    iosClientId: '253020332110-e92n5t9hvur0bh1nn8ess652102ba0r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittnesFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXGcIsol6oNff_X93LGqE8AN9uFOiE_HU',
    appId: '1:253020332110:web:809a2f294830a8ee0ae31f',
    messagingSenderId: '253020332110',
    projectId: 'fitness-app-89b40',
    authDomain: 'fitness-app-89b40.firebaseapp.com',
    storageBucket: 'fitness-app-89b40.appspot.com',
    measurementId: 'G-03RNK9MZRP',
  );
}
