name: Admin Coach Frontend Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd ./admin_coach_frontend/admin-coach-frontend
          npm ci

      - name: Build the project
        run: |
          cd ./admin_coach_frontend/admin-coach-frontend
          CI=false npm run build --if-present

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./admin_coach_frontend/admin-coach-frontend
          file: ./admin_coach_frontend/admin-coach-frontend/Dockerfile
          push: true
          tags: tudormiron/fitness-app-admin-coach-frontend:1.0.3
