name: chat-service

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd ./chat-service
          npm install

      - name: Build the project
        run: |
          cd ./chat-service
          npm run build
        env:
          NODE_ENV: production

      - name: Archive node_modules
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: ./chat-service/node_modules

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: ./chat-service

      - name: Run tests
        run: |
          cd ./chat-service
          npm test

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./chat-service
          file:  ./chat-service/Dockerfile
          push: true
          tags: tudormiron/chat-service:1.0.0
