apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: authorization-app-img-conf
  namespace: flux-system
spec:
  image: docker.io/tudormiron/fitness-app-authorization
  interval: 1m